// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elofhyypbxsdxlhfdefp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsb2ZoeXlwYnhzZHhsaGZkZWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTgwODUsImV4cCI6MjA2MDgzNDA4NX0.QAGzXuEFsTJ-szpl5ykatmJ3cdQNGAQ-h9koUSQUFkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);